version: 2
jobs:
  # working_directory: ${WORK_DIRECTORY}

  test:
    docker:
      - image: circleci/golang:1.14

    environment: # environment variables for the build itself
      TEST_RESULTS: /go/test-results # path to where test results will be saved
      # WORK_DIRECTORY: /go/src/${CIRCLE_BRANCH}

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: deps test
          command: make test

      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: circleci/golang:1.14

    environment: # environment variables for the build itself
      TEST_RESULTS: /go/test-results # path to where test results will be saved
      # WORK_DIRECTORY: /go/src/${CIRCLE_BRANCH}

    steps:
      - attach_workspace:
          at: .

      - run:
          name: buiid
          command: make build

  # publish-github-release:
  #   docker:
  #     - image: circleci/golang:1.14
  #   steps:
  #     - attach_workspace:
  #         at: ./bin
  #     - run: ls -laR
  #     - run:
  #         name: "Publish Release on GitHub"
  #         command: |
  #           go get github.com/tcnksm/ghr
  #           VERSION=v0.9.0
  #           # ghr -t ${GITHUB_TOKEN} -delete ${VERSION} ./bin/
  #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      # - publish-github-release
